### ISSUE TITLE
Invalid magic number signing provisioning profile

### ISSUE THREAD

**Issue by hneiva** [indygreg/apple-platform-rs#13]
(this might be a duplicate of indygreg/apple-platform-rs#10)
I'm seeing the "invalid magic number" error when dealing with provisioning profiles.

```
$ rcodesign sign -v --p12-file /opt/cert/certs/prod.p12 --team-name [redacted] embedded.provisionprofile
Please enter password for p12 file: [hidden]
[2022-08-26T15:31:24Z WARN  rcodesign] registering signing key
[2022-08-26T15:31:24Z WARN  rcodesign] automatically registered Apple CA certificate: Developer ID Certification Authority
[2022-08-26T15:31:24Z WARN  rcodesign] automatically registered Apple CA certificate: Apple Root CA
[2022-08-26T15:31:24Z WARN  rcodesign] using time-stamp protocol server http://timestamp.apple.com/ts01
[2022-08-26T15:31:24Z WARN  rcodesign] automatically setting team ID from signing certificate: [redacted]
[2022-08-26T15:31:24Z WARN  rcodesign] signing embedded.provisionprofile in place
[2022-08-26T15:31:24Z WARN  rcodesign::signing] signing embedded.provisionprofile as a Mach-O binary
[2022-08-26T15:31:24Z INFO  rcodesign::signing_settings] inferring default signing settings from Mach-O binary
Error: binary parsing error: Invalid magic number: 0x30823224
```
I verified this happens with multiple provisioning profiles.
The problem also shows up when a bundle with an inner .app has a provisioning profile.

Apple's `codesign` is able to sign these standalone files, and the app bundle with inner profile.

Any way I can get more info on why this is happening? (adding `RUST_BACKTRACE=full` doesn't show anything extra info in my case)

Ps: Running on docker debian bullseye + rcodesign 0.17.0 (installed via cargo)

**Comment by indygreg** [comment]
Thanks for filing this.

I agree this might be in the same camp as #10. But the separate bug report is very much appreciated!

I haven't tested provisioning profiles that much. I'm unsure if they need to be handled specially or what. But if this is like #10, the problem is we're treating the file as a Mach-O when it isn't a Mach-O and then everything just fails.

Do you have an Apple signed bundle for me to take a look at to see how Apple's tooling handles this case?

**Comment by roblabla** [comment]
I don't understand this bug report. Why are you trying to sign a provisionprofile file? The provisionprofile isn't supposed to get signed, afaict. I'm not sure what apple codesign does with it (I tested locally, and it doesn't error out, but it doesn't modify the file in any way, nor outputs any logs...)

AFAICT, you're supposed to place the provisionprofile inside a `.app` bundle, next to the Info.plist file, like so:

<img width="773" alt="image" src="https://user-images.githubusercontent.com/1069318/191008042-c9bcce9a-da4f-4403-994b-b6b8168a77f9.png">

I sign my app with this structure using rcodesign without any issue.

**Comment by hneiva** [comment]
@indygreg I encountered this error trying to sign MozillaVPN.
You can find some builds here: https://treeherder.mozilla.org/jobs?repo=mozilla-vpn-client&searchStr=signing-macos
(link with search for signing-macos tasks only - build-macos tasks will have the tarball with the .app)

I'm thinking rcodesign identifies the root app profile, but when it's signing a child .app, it sees its profile as Mach-O..?

@roblabla when you sign the outer app, it signs everything inside of it. I couldn't get the `--exclude` flag to work and ignore provisioning profiles. @indygreg, is this flag supposed to work?

**Comment by indygreg** [comment]
I attempted to reproduce this using the latest MozillaVPN.tar.gz from Treeherder and it looks like it now signs correctly. I suspect the fix was in the latest release or in some additional bug fixes on the `main` branch.

FWIW I was able to resign Firefox.app with rcodesign as well. Although I haven't tested notarization yet. Please file new issues for any problems signing Mozilla products: I'm eager to onboard you as a customer because I know how painful the Mac Mini code signing machines are for you to operate.

**Comment by hneiva** [comment]
That's amazing news! Thank you so much!
I've switched the notarization of Firefox to rcodesign in linux[1] already and it's been working great, I'll investigate switching signing as well.

[1] https://treeherder.mozilla.org/jobs?repo=mozilla-central&searchStr=build-mac-notarization

**Comment by hafta** [comment]
Yes, this is really cool. Thanks @indygreg! With the latest version, I just got a Firefox build to sign with rcodesign and successfully notarize.
