### ISSUE TITLE
Error: binary parsing error: Invalid magic number: 0x504b0304

### ISSUE THREAD

**Issue by loskiq** [indygreg/apple-platform-rs#29]
```
root@debian:~/build# rcodesign sign --p12-file iphone_dev.p12 --code-signature-flags runtime /root/build/app.ipa
Please enter password for p12 file: [hidden]
registering signing key
automatically registered Apple CA certificate: Apple Worldwide Developer Relations Certification Authority
automatically registered Apple CA certificate: Apple Root CA
using time-stamp protocol server http://timestamp.apple.com/ts01
automatically setting team ID from signing certificate: 65MQZ3ZCVL
signing /root/build/app.ipa in place
signing /root/build/app.ipa as a Mach-O binary
inferring default signing settings from Mach-O binary
Error: binary parsing error: Invalid magic number: 0x504b0304
root@debian:~/build#
```

What am I doing wrong?

**Comment by roblabla** [comment]
Hmm, I don't think rcodesign supports signing IPAs yet. So that's probably the issue here.

IPAs are ZIP files that contain the application (the .app) under the Payload folder (e.g. `/Payload/Application.app/`) along with some metadata next to it (such as artwork for the apple store).

As far as I know, IPA doesn't have any actual codesigning - the only thing that needs to be codesigned is the application contained within. So when rcodesign encounters an IPA, it should simply codesign the contained application.

**Comment by indygreg** [comment]
We don't yet support signing IPAs directly nor in their extracted form (unless you sign the bundle file).

We should probably add support for natively signing IPAs. We can track that in a separate issue.

I'd like to keep this issue open to track the apparent false-positive of identifying a zip file as a Mach-O binary. I think the problem here is that the first entry in the zip is a Mach-O and this makes the signing code think it is a Mach-O. (Zip files have their header at the end of the file.)

This false positive may no longer produce in `main` after commit 66b57c82ed6982b94710794034d11a6d8104969d, as that commit added code to explicitly test for zip files. So we may no longer fall back to the code that is falsely identifying an IPA as a Mach-O.

**Comment by indygreg** [comment]
Commit 1c63bcabc5c77a025b91412a2f132e120be41756 should have fixed Mach-O false positives leading to `Invalid magic number` errors. I'm going to close this issue on the assumption it is closed.

IPA signing has its own issue tracked at #30. Please reopen if this is still a problem.
