### ISSUE TITLE
Error: signature data too large (please report this issue)

### ISSUE THREAD

**Issue by diamantisk** [indygreg/apple-platform-rs#32]
While trying to sign a binary with p12 certificate and a plist file (somehow large), I'm getting the following error:
Error: signature data too large (please report this issue)

If I remove some keys from the plist file it seems to work. But on the other hand, while I evolved the rust code a bit more, it seems that I have to remove more data from the plist file now.

Is this an issue? Or I'm doing something wrong?

The command is: rcodesign sign --entitlements-xml-path rustswift.entitlements --p12-file Certificates.p12 --p12-password Certificate --runtime-version 12.3.0   ./target/debug/rustswift

**Comment by indygreg** [comment]
We have to estimate the size of the final signature to reserve space for it.

The bug here is that code (`estimate_embedded_signature_size()` in `macho.rs`) doesn't account for the embedded plist data. (The code is also not very precise and I'm somewhat surprised it took this long for someone to find an issue!)

There are some other pieces of data (e.g. designated requirements) that it also fails to account for. See `create_special_blobs()` in `macho_signing.rs`. But the plist is likely the only one large enough to cause us to overrun the extra padding we provide.

The quick fix here is adding code similar to https://github.com/indygreg/apple-platform-rs/blob/ae5f055100b5c7c2099b3c0c1c0a4441604929f9/apple-codesign/src/macho_signing.rs#L641 to `estimate_embedded_signature_size()` to increase the estimated size to account for the XML and DER encoded plist data.

**Comment by indygreg** [comment]
Should be fixed by #40.
