### ISSUE TITLE
Slight difference between the _CodeSignature/CodeResources file in the rules section for .lproj localized bundles.

### ISSUE THREAD

**Issue by catshow** [indygreg/apple-platform-rs#42]
The original from macOS codesign tool produced the output on the left side of the image, the one on the right was from this project.

<img width="1126" alt="image" src="https://user-images.githubusercontent.com/56951/200143267-8556f577-19b0-4f68-87c8-d98c53ab4540.png">

**Comment by catshow** [comment]
Here is a patch.

```diff
diff --git a/apple-codesign/src/code_resources.rs b/apple-codesign/src/code_resources.rs
index c2eba2cb..547d4ad4 100644
--- a/apple-codesign/src/code_resources.rs
+++ b/apple-codesign/src/code_resources.rs
@@ -1037,11 +1037,11 @@ impl CodeResourcesBuilder {
         slf.add_rule(CodeResourcesRule::new("^version.plist$")?);
         slf.add_rule(CodeResourcesRule::new("^.*")?);
         slf.add_rule(
-            CodeResourcesRule::new("^.*\\.lproj")?
+            CodeResourcesRule::new("^.*\\.lproj/")?
                 .optional()
                 .weight(1000),
         );
-        slf.add_rule(CodeResourcesRule::new("^Base\\.lproj")?.weight(1010));
+        slf.add_rule(CodeResourcesRule::new("^Base\\.lproj/")?.weight(1010));
         slf.add_rule(
             CodeResourcesRule::new("^.*\\.lproj/locversion.plist$")?
                 .omit()
@@ -1063,7 +1063,7 @@ impl CodeResourcesBuilder {
                 .optional()
                 .weight(1000),
         );
-        slf.add_rule2(CodeResourcesRule::new("^Base\\.lproj")?.weight(1010));
+        slf.add_rule2(CodeResourcesRule::new("^Base\\.lproj/")?.weight(1010));
         slf.add_rule2(
             CodeResourcesRule::new("^.*\\.lproj/locversion.plist$")?
                 .omit()
```

**Comment by indygreg** [comment]
Thanks for the report.

These default patterns are defined around https://github.com/indygreg/apple-platform-rs/blob/c421809ffaf71d189e3e7fbe8c589ae5718b6c1f/apple-codesign/src/code_resources.rs#L984.

But, I think the bug is likely around our logic choosing which set of rules to use. We already have a comment calling out doubt over our heuristic: https://github.com/indygreg/apple-platform-rs/blob/c421809ffaf71d189e3e7fbe8c589ae5718b6c1f/apple-codesign/src/bundle_signing.rs#L476.

Now that we have an example differing case, perhaps we should tweak the heuristic...

**Comment by catshow** [comment]
I can't contribute to the project right now, but the fix I made was just to the string values in the rules and rules2.
