### ISSUE TITLE
Feature request: implement a digest caching layer instead of reading entire file into memory for the CodeResources.

### ISSUE THREAD

**Issue by catshow** [indygreg/apple-platform-rs#45]
It appears that the CodeResources logic is reading the entire file into memory then calling the appropriate digest.  This will be very memory intensive for large applications with lots of resources.

One should just take a path to the file and compute and store the cached checksum vectors into the cache.  In my implementation, I am computing both the SHA-1 and SHA-256 simultaneously, and I also copy the file into the target directory if needed, so I only read the file once.

Maybe hold off on implementing this.  I will try to get clearance from my employer to submit my changes back to the project.

**Comment by indygreg** [comment]
I initially implemented everything in memory because it made things simpler - you could just take slices of raw data without having to read or seek file streams. Plus the Rust Mach-O parsers really want you to have the full Mach-O in memory for parsing.

But for digesting files in bundles, there's really no excuse to read to memory first. Although if we move to digesting from a file, we'll have to rework our `rayon` code for parallel digest calculation. This doesn't seem too bad though.

I'll gladly take patches to make it so we can sign large files without excessive memory utilization.

**Comment by indygreg** [comment]
I implemented file streaming + multi-hashing for non Mach-O binaries in 3576f924dd31731cbb5554784a836888151669bd. If these optimizations aren't sufficient for your performance, please file a new issue.
